export const WITHDRAW_TYPES = {
    ADD_WITHDRAW_DATA: 'ADD_WITHDRAW_DATA',
    CLEAN_WITHDRAW_DATA: 'CLEAN_WITHDRAW_DATA',
    ADD_WITHDRAW_SECURITY_STEP: 'ADD_WITHDRAW_SECURITY_STEP',
    CLEAR_WITHDRAW_SECURITY_STEP: 'CLEAR_WITHDRAW_SECURITY_STEP',
    ADD_BIOMETRIC_DATA: 'ADD_BIOMETRIC_DATA',
    CLEAR_BIOMETRIC_DATA: 'CLEAR_BIOMETRIC_DATA',
    ADD_QNA_DATA: 'ADD_QNA_DATA',
    CLEAR_QNA_DATA: 'CLEAR_QNA_DATA',
    CLEAR_DATA: 'CLEAR_DATA',
};